<?php

$rules = [
    'IMP-R001' => 'Import mutations must use TenantDataImportService.',
    'IMP-R002' => 'Import must be tenant-isolated.',
    'IMP-R003' => 'Import must be dry-run by default.',
    'IMP-R004' => 'Execute import must require explicit execute flag and authorization.',
    'IMP-R005' => 'Import run must have unique idempotency key.',
    'IMP-R006' => 'Row processing must be idempotent through row fingerprint.',
    'IMP-R007' => 'Retry must not duplicate records.',
    'IMP-R008' => 'CSV import must be supported.',
    'IMP-R009' => 'XLSX import must be safe, formula-safe, macro-safe, or explicitly governed/deferred.',
    'IMP-R010' => 'Import validation must happen before mutation.',
    'IMP-R011' => 'Validation errors must be row-addressable and redacted.',
    'IMP-R012' => 'Failed import must leave auditable failed state.',
    'IMP-R013' => 'Import rollback must be safe and limited to records created by the import run.',
    'IMP-R014' => 'Product import must not bypass product/domain service if one exists.',
    'IMP-R015' => 'Category import must be deterministic and tenant-isolated.',
    'IMP-R016' => 'Supplier import must redact PII in output/audit.',
    'IMP-R017' => 'Customer import must redact PII in output/audit.',
    'IMP-R018' => 'Initial stock import must use inventory movement/ledger service where available.',
    'IMP-R019' => 'Initial stock import must never directly corrupt stock balances.',
    'IMP-R020' => 'Price import must use existing pricing/product price service where available.',
    'IMP-R021' => 'Payment method/default settings import must be tenant-scoped.',
    'IMP-R022' => 'Bootstrap pack must integrate with Sprint 33 onboarding state.',
    'IMP-R023' => 'Import denied/blocked actions must be audit-logged.',
    'IMP-R024' => 'Support console must be able to inspect import runs safely.',
    'IMP-R025' => 'Observability must detect failed/stuck imports.',
    'IMP-R026' => 'Import output must not leak secrets/PII/raw file contents.',
    'IMP-R027' => 'Import must not mark invoices paid.',
    'IMP-R028' => 'Import must not unlock entitlement.',
    'IMP-R029' => 'Import must not bypass manual suspension.',
    'IMP-R030' => 'Import must respect Sprint 32 entitlement write state where applicable.',
    'IMP-R031' => 'Import must not reactivate device/tenant.',
    'IMP-R032' => 'Platform-admin bypass must be explicit and audited.',
    'IMP-R033' => 'Prior Sprint 24-36 gates must remain green.',
    'IMP-R034' => 'Go/no-go must verify import coverage, rollback, audit, support, observability, and redaction.',
];

return [
    'enabled' => true,
    'platform_admin_enabled' => true,
    'tenant_side_import_enabled' => false,
    'dry_run_default' => true,
    'execute_requires_explicit_flag' => true,
    'execute_requires_reason' => true,
    'execute_requires_idempotency_key' => true,
    'supported_formats' => ['csv'],
    'xlsx' => [
        'supported' => false,
        'deferred_reason' => 'No safe lightweight XLSX parser is installed; macros/formulas are rejected and CSV templates are authoritative.',
    ],
    'max_file_size_bytes' => 2 * 1024 * 1024,
    'max_rows' => 1000,
    'import_types' => ['category', 'product', 'supplier', 'customer', 'initial_stock', 'price', 'payment_method', 'default_settings', 'bootstrap_pack'],
    'required_headers' => [
        'category' => ['name'],
        'product' => ['sku', 'name', 'selling_price'],
        'supplier' => ['code', 'name'],
        'customer' => ['code', 'name'],
        'initial_stock' => ['sku', 'store_code', 'qty'],
        'price' => ['sku', 'store_code', 'selling_price'],
        'payment_method' => ['code', 'name', 'method_type'],
        'default_settings' => ['setting_key', 'setting_value'],
        'bootstrap_pack' => ['section', 'code', 'name'],
    ],
    'duplicate_matching' => [
        'category' => ['tenant_id', 'store_id', 'name'],
        'product' => ['tenant_id', 'sku'],
        'supplier' => ['tenant_id', 'code'],
        'customer' => ['tenant_id', 'code'],
        'initial_stock' => ['tenant_id', 'store_id', 'sku', 'row_fingerprint'],
        'price' => ['tenant_id', 'store_id', 'sku'],
        'payment_method' => ['tenant_id', 'code'],
        'default_settings' => ['tenant_id', 'setting_key'],
    ],
    'idempotency' => [
        'run_key_unique' => true,
        'row_fingerprint_unique_per_run' => true,
        'algorithm' => 'sha256',
    ],
    'rollback' => [
        'created_records_only' => true,
        'stock_delete_allowed' => false,
        'stock_reversal_supported' => true,
    ],
    'redaction' => [
        'required' => true,
        'redact_metadata' => true,
        'redacted_value' => '[REDACTED]',
    ],
    'audit' => [
        'required' => true,
        'admin_audit' => true,
        'actions' => ['started', 'validated', 'executed', 'failed', 'rolled_back', 'denied'],
    ],
    'observability' => [
        'failed_import_anomaly_enabled' => true,
        'stuck_import_minutes' => 30,
    ],
    'rules' => $rules,
    'required_docs' => [
        'docs/architecture/sprint-37-data-import-migration-first-tenant-bootstrap-pack.md',
        'docs/sprints/sprint-37-data-import-migration-first-tenant-bootstrap-pack-evidence.md',
    ],
    'commands' => [
        'import:template',
        'import:validate',
        'import:execute',
        'import:summary',
        'import:rows',
        'import:rollback',
        'import:bootstrap-pack',
        'import:governance-audit',
        'import:go-no-go',
    ],
];
