<?php

$rules = [
    'PERF-R001' => 'Performance benchmarks must use PerformanceBenchmarkService.',
    'PERF-R002' => 'Benchmark fixtures must be deterministic.',
    'PERF-R003' => 'Benchmark data must be tenant-isolated.',
    'PERF-R004' => 'CI profile must be bounded and non-flaky.',
    'PERF-R005' => 'Heavy profile must not run by default in CI.',
    'PERF-R006' => 'Performance commands must require explicit profile.',
    'PERF-R007' => 'Destructive cleanup must be limited to benchmark-created data.',
    'PERF-R008' => 'Benchmark output must not leak PII, secrets, or raw payloads.',
    'PERF-R009' => 'Many-tenant benchmark must verify tenant isolation.',
    'PERF-R010' => 'Product benchmark must verify product/category lookup performance.',
    'PERF-R011' => 'POS transaction benchmark must use the existing SaleService/domain service.',
    'PERF-R012' => 'POS benchmark must not double-create transactions.',
    'PERF-R013' => 'Android sync benchmark must use Sprint 34 sync service and idempotency.',
    'PERF-R014' => 'Import benchmark must use Sprint 37 DataImport services.',
    'PERF-R015' => 'Export/report benchmark must preserve Sprint 27-29 metering/governance.',
    'PERF-R016' => 'Billing benchmark must use Sprint 30 invoice/collection services.',
    'PERF-R017' => 'Payment webhook benchmark must use Sprint 31 mock/safe gateway events.',
    'PERF-R018' => 'Entitlement benchmark must use Sprint 32 EntitlementAccessService.',
    'PERF-R019' => 'Onboarding benchmark must preserve Sprint 33 provisioning semantics.',
    'PERF-R020' => 'Support diagnostics benchmark must preserve Sprint 35 read-only support semantics.',
    'PERF-R021' => 'Observability benchmark must integrate Sprint 36 metrics/anomaly services.',
    'PERF-R022' => 'Queue pressure benchmark must not require external queue infra in CI.',
    'PERF-R023' => 'Failed job diagnostics must remain redacted under load.',
    'PERF-R024' => 'Index additions must be justified by query pattern evidence.',
    'PERF-R025' => 'Index review must not remove prior indexes without explicit proof.',
    'PERF-R026' => 'Threshold gate must fail closed on regression.',
    'PERF-R027' => 'Threshold gate must produce explainable reason codes.',
    'PERF-R028' => 'Benchmark snapshots must be auditable and redacted.',
    'PERF-R029' => 'Performance smoke must run in CI.',
    'PERF-R030' => 'Deploy performance smoke must run after pilot/VPS deployment.',
    'PERF-R031' => 'No benchmark may mark invoice paid outside trusted billing/payment services.',
    'PERF-R032' => 'No benchmark may unlock entitlement outside trusted collection state.',
    'PERF-R033' => 'No benchmark may bypass manual suspension.',
    'PERF-R034' => 'No benchmark may reactivate tenant/device.',
    'PERF-R035' => 'Prior Sprint 24-37 gates must remain green.',
    'PERF-R036' => 'Go/no-go must verify multi-tenant, product, POS, Android sync, import, export/report, billing/payment, queue, index/query, observability, smoke-performance, and deploy evidence.',
];

return [
    'default_profile' => 'ci_smoke',
    'profiles' => [
        'ci_smoke' => [
            'tenant_count' => 3,
            'product_count' => 12,
            'pos_transaction_count' => 6,
            'android_sync_batch_count' => 2,
            'android_sync_item_count' => 8,
            'import_row_count' => 10,
            'export_report_row_count' => 20,
            'payment_webhook_event_count' => 6,
            'queue_job_count' => 8,
            'thresholds' => ['max_runtime_ms' => 60000, 'max_average_query_count' => 250, 'max_p95_duration_ms' => 3000, 'max_failed_jobs' => 0, 'max_anomaly_count' => 0, 'max_memory_mb' => 256, 'max_duplicate_sync_sale_count' => 0],
        ],
        'local_medium' => [
            'tenant_count' => 10,
            'product_count' => 100,
            'pos_transaction_count' => 80,
            'android_sync_batch_count' => 10,
            'android_sync_item_count' => 100,
            'import_row_count' => 250,
            'export_report_row_count' => 500,
            'payment_webhook_event_count' => 50,
            'queue_job_count' => 100,
            'thresholds' => ['max_runtime_ms' => 300000, 'max_average_query_count' => 1500, 'max_p95_duration_ms' => 7500, 'max_failed_jobs' => 0, 'max_anomaly_count' => 2, 'max_memory_mb' => 512, 'max_duplicate_sync_sale_count' => 0],
        ],
        'pilot_vps' => [
            'tenant_count' => 15,
            'product_count' => 300,
            'pos_transaction_count' => 150,
            'android_sync_batch_count' => 20,
            'android_sync_item_count' => 250,
            'import_row_count' => 1000,
            'export_report_row_count' => 1500,
            'payment_webhook_event_count' => 150,
            'queue_job_count' => 250,
            'thresholds' => ['max_runtime_ms' => 600000, 'max_average_query_count' => 3000, 'max_p95_duration_ms' => 12000, 'max_failed_jobs' => 0, 'max_anomaly_count' => 3, 'max_memory_mb' => 768, 'max_duplicate_sync_sale_count' => 0],
        ],
        'manual_heavy' => [
            'tenant_count' => 50,
            'product_count' => 2000,
            'pos_transaction_count' => 2000,
            'android_sync_batch_count' => 100,
            'android_sync_item_count' => 5000,
            'import_row_count' => 20000,
            'export_report_row_count' => 50000,
            'payment_webhook_event_count' => 2000,
            'queue_job_count' => 5000,
            'thresholds' => ['max_runtime_ms' => 7200000, 'max_average_query_count' => 50000, 'max_p95_duration_ms' => 30000, 'max_failed_jobs' => 0, 'max_anomaly_count' => 10, 'max_memory_mb' => 2048, 'max_duplicate_sync_sale_count' => 0],
        ],
    ],
    'index_review_policy' => 'Observe query patterns first; record evidence before adding indexes; never remove prior indexes without proof.',
    'observability_policy' => 'Bridge benchmark snapshots into Sprint 36 observability using redacted metrics only.',
    'deploy_gate_policy' => 'Pilot/VPS deploy evidence is mandatory before Sprint 38 GO; missing deploy credentials are BLOCKED, not success.',
    'rules' => $rules,
    'commands' => [
        'performance:profile-summary',
        'performance:fixture-build',
        'performance:run',
        'performance:threshold-check',
        'performance:query-review',
        'performance:queue-pressure',
        'performance:smoke',
        'performance:deploy-check',
        'performance:governance-audit',
        'performance:go-no-go',
    ],
];
