<?php

/**
 * Foundation metadata (not runtime logic). Locks the canonical document and
 * the cumulative sprint rules so tooling/tests can assert they are wired.
 * See docs/foundation/POS_ANDROID_SAAS_FOUNDATION.md and docs/PROJECT_RULES.md.
 */
return [
    'foundation_document' => 'docs/foundation/POS_ANDROID_SAAS_FOUNDATION.md',
    'project' => 'Aish POS Lite',
    'rules' => [
        'multi_tenant' => true,
        'backend_payment_only' => true,
        'android_lightweight' => true,
        'offline_cash_only' => true,
        'qris_online_only' => true,
        'tenant_isolation_required' => true,
        'product_sync_required' => true,
        'android_cashier_foundation_required' => true,
        'android_local_catalog_required' => true,
        'sales_backend_required' => true,
        'cash_payment_backend_required' => true,
        'qris_not_in_sprint_4' => true,
        'qris_backend_driven_required' => true,
        'qris_webhook_ready_required' => true,
        'payment_gateway_credentials_backend_only' => true,
        'receipt_backend_authoritative' => true,
        'escpos_android_formatter_required' => true,
        'android_gradle_wrapper_required' => true,
        'android_build_ci_required' => true,
        'offline_qris_forbidden' => true,
        'sales_idempotency_required' => true,
        'workmanager_sync_required' => true,
        'inventory_ledger_only' => true,
        'sale_out_movement_required' => true,
        'inventory_current_stock_from_movements' => true,
        'inventory_idempotency_safe' => true,
        'reports_backend_authoritative' => true,
        'daily_closing_required' => true,
        'closing_snapshot_lock_required' => true,
        'csv_export_tenant_isolated' => true,
        'subscription_required' => true,
        'device_limit_required' => true,
        'device_registration_backend_enforced' => true,
        'subscription_billing_not_in_sprint_10' => true,
        'platform_admin_required' => true,
        'admin_audit_log_required' => true,
        'admin_no_tenant_impersonation_sprint_11' => true,
        'admin_no_real_billing_collection_sprint_11' => true,
        'admin_no_tenant_hard_delete_sprint_11' => true,
        'tenant_onboarding_platform_admin_only' => true,
        'tenant_onboarding_idempotent_required' => true,
        'demo_data_tenant_isolated_required' => true,
        'demo_reset_guard_required' => true,
        'onboarding_audit_log_required' => true,
        'onboarding_no_public_signup_sprint_12' => true,
        'onboarding_no_real_billing_sprint_12' => true,
        'onboarding_no_invite_automation_sprint_12' => true,
    ],
    'sprints' => [
        'sprint_0' => 'Project Setup',
        'sprint_1' => 'SaaS Tenant Foundation',
        'sprint_2' => 'Product Foundation',
        'sprint_3' => 'Android Cashier Foundation',
        'sprint_4' => 'Sales Backend Integration',
        'sprint_5' => 'QRIS Payment Gateway Foundation',
        'sprint_6' => 'Printer & Receipt Foundation',
        'sprint_7' => 'Offline Cash & Sync Foundation',
        'sprint_8' => 'Inventory Simple Foundation',
        'sprint_9' => 'Reports & Closing Foundation',
        'sprint_10' => 'Subscription & Device Limit Foundation',
        'sprint_11' => 'Admin SaaS Control Panel Foundation',
        'sprint_12' => 'Tenant Onboarding & Demo Data Foundation',
    ],
];
